version: 0.0
os: linux
files:
  - source: /

    destination: /home/ec2-user/deploy/
    overwrite: true
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/build_vue_app
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_vue_app
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_vue_app
      timeout: 300
      runas: root