version: 0.2

phases:


  build:
    commands:
      - npm install
      - npm run build

artifacts:
  files:
    - dist/**/*
    - public/**/*
    - src/**/*
    - package.json
    - appspec.yml
    - scripts/**/*
