version: 0.2

phases:
  pre_build:
    commands:
      - nvm install 12
      - npm install -g npm@7

  build:
    commands:
      - npm install
      - npm run build

artifacts:
  files:
    - dist/**/*
    - package.json
    - appspec.yml
    - scripts/**/*
