version: 0.2

phases:
  install:
    commands:
      - echo Updating npm
      - npm update -g npm
      - echo Installing jQuery Bootstrap-Vue
      - npm install 
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'