version: 0.3

phases:
  install:
    commands:
      - echo Updating npm
      - npm update -g npm
      - echo Installing jQuery Bootstrap-Vue
      - npm install --save jquery bootstrap-vue
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'