version: 0.2

phases:


  build:
    commands:
      - npm install
      - npm run build

artifacts:
  files:
    - dist/**/*
    - public/**/*
    - src/**/*
    - package.json
    - appspec.yml
    - scripts/build_vue_app.sh
    - scripts/start_vue_app.sh
    - scripts/stop_vue_app.sh
    - scripts/install_dependencies.sh