version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.15
  aws-cli: circleci/aws-cli@3.1.1

jobs:
  authenticate-ecr:
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
          profile-name: my-profile
      - run:
          name: Authenticate with ECR
          command: aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY_URL

  build-and-deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Build and push Docker image
          command: |
            # Your Docker build and push commands here

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - authenticate-ecr
      - build-and-deploy:
          requires:
            - authenticate-ecr
