#!/bin/bash


sudo yum update
sudo yum install -y apt
sudo yum install -y nodejs npm

# Change to the directory where package.json is located


# Check if package.json exists before running npm commands
#if [ -f "package.json" ]; then
  npm install
#else
  #echo "No package.json found. Skipping npm commands."
#fi
